# **Курс "Програмування на мові Python"**

##### Викладачі:
##### Борисенко Павло Борисович
##### Щьоголєв Максим Олегович


## **Практичне зайняття №8**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажання можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [3]:
import numpy as np
import itertools

def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix

def coordinates(n):
    """
    Функція визначає координати елементів матриці,
    в порядку їх подальшого перебору методом перестановки
    """
    t = list(itertools.permutations(range(n), n))
    lst=[]
    # генеруємо список з координатами елементів
    for i in range(len(t)):
        for j in range(n):
            lst.append([j, t[i][j]])
    return lst

def znak(lst):
    """
    Функція визначає знак майбутнього добутку
    за кількістю перестановок рядків у матриці
    """
    z = []  # список елементів на визначення перестановок
    p = 0  # лічильник на +-
    q=[]

    for i in range(len(lst)):
        z.append(lst[i][1])
        if (i + 1) % n == 0 and i != 0:
            for l in range(n - 1):
                for j in range(n - l - 1):
                    if z[j] > z[j + 1]:
                        p += 1
                        z[j], z[j + 1] = z[j + 1], z[j]
            if p % 2 == 0:
                q.append(1)

            else:
                q.append(0)
            z, p = [], 0
    return q

def Spysok_perestan(lst,k):
    """
    Функція, у якій під вже відомі координати перебору
    підставляються реальні елементи
    """
    lst2=[]
    #генеруємо список із елементами матриці в порядку майбутнього множення(додавання) за способом зміни рядків
    for i in range(len(lst)):
        lst2.append(k[lst[i][0]][lst[i][1]])
    return lst2 #повертає всіх перебраних елементів

def dobytky(lst):
    """
    Функція повертає значення всіх добутків,
    які потім будуть додаватися для знаходження визначника
    """
    lt = [] # список із добутками
    p=1
    for i in range(len(lst)):
        p*=lst[i]
        if (i+1)%n==0:
            lt.append(p)
            p=1
    return lt #повертає добуток переборів

def det(z,d):
    """
    Функція, у якій в добутках елементів вже враховується знак.
    Знаходиться сума, сам визначник матриці
    """
    sum=0
    for i in range(len(z)):
        if z[i]==0:
            d[i]=-d[i]
        sum+=d[i]
    return sum


n=int(input("Enter the n: "))

k=random_matrix(n)

print("Your matrix=\n", k)

coor=coordinates(n)

per=Spysok_perestan(coor,k)

dob=dobytky(per)

print("det=",det(znak(coor),dob))

Enter the n: 5
Your matrix=
 [[3 1 2 8 9]
 [0 7 5 3 6]
 [9 9 5 8 5]
 [6 7 8 5 4]
 [8 8 1 1 3]]
det= 12788
